// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package config

import (
	"klik/controllers"
	"klik/repository"
	"klik/service"
	"gorm.io/gorm"
)

// Injectors from di.go:

func InjectUserController(db *gorm.DB) controllers.UserController {
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	userController := controllers.NewUserController(userService)
	return userController
}

func InjectAuthController(db *gorm.DB) controllers.AuthController {
	userRepository := repository.NewUserRepository(db)
	authService := service.NewAuthService(userRepository)
	authController := controllers.NewAuthController(authService)
	return authController
}

func InjectMenuController(db *gorm.DB) controllers.MenuController {
	menuRepository := repository.NewMenuRepository(db)
	menuService := service.NewMenuService(menuRepository)
	menuController := controllers.NewMenuController(menuService)
	return menuController
}

func InjectRoleController(db *gorm.DB) controllers.RoleController {
	repository := repository.NewRoleRepository(db)
	service := service.NewRoleService(repository)
	controller := controllers.NewRoleController(service)
	return controller
}

func InjectProductController(db *gorm.DB) controllers.ProductController {
	repository := repository.NewProductRepository(db)
	service := service.NewProductService(repository)
	controller := controllers.NewProductController(service)
	return controller
}